<h1>AltLaw Admin</h1>
<p><a href="/admin/norobots">Docid no robots</a></p>

<form action="/admin/update-code" method="post">
<p><input type="submit" value="Update Source Code"/></p>
</form>

<form action="/admin/recompile" method="post">
<p><input type="submit" value="Recompile"/></p>
</form>

<form action="/admin/make-content-pages" method="post">
<p><input type="submit" value="Rebuild Content Pages"/></p>
</form>

<form action="/admin/restart-app" method="post">
<p><input type="submit" value="Restart Application"/></p>
</form>

