<h1>AltLaw Admin</h1>
<p><a href="/admin/norobots">Docid no robots</a></p>

<form action="/admin/update-code" method="post">
<input type="hidden" name="command" value="command"/>
<p><input type="submit" value="Update Source Code"/></p>
</form>

<form action="/admin/recompile" method="post">
<input type="hidden" name="command" value="command"/>
<p><input type="submit" value="Recompile"/></p>
</form>

<form action="/admin/make-content-pages" method="post">
<input type="hidden" name="command" value="command"/>
<p><input type="submit" value="Rebuild Content Pages"/></p>
</form>

