<h2>Information</h2>

<ul>
  <li><a href="/v1/about">About This Site</a></li>
  <li><a href="/v1/about/beta">What Does &lsquo;BETA&rsquo; Mean?</a></li>
  <li><a href="/v1/about/press">Press &amp; Blogging</a></li>
  <li><a href="/v1/about/why">Why Is My Case Here?</a></li>
</ul>

<h2>Research</h2>

<ul>
  <li><a href="/v1/about/coverage">Case Coverage</a></li>
  <li><a href="/v1/about/search-toolbar">AltLaw in Your Toolbar</a></li>
  <li><a href="/v1/about/others">Other Free Legal Sites</a></li>
</ul>

<h2>Get Involved</h2>

<ul>
  <li><a href="/v1/about/feedback">Send Feedback</a></li>
  <li><a href="/v1/about/contribute">Contribute to AltLaw</a></li>
</ul>
